[tox]
minversion = 4.0
skipsdist = true
envlist =
    py3
    black
    flake8
    isort

[testenv]
usedevelop = true
passenv = DJANGO_SETTINGS_MODULE,PYTHONPATH,HOME,DISPLAY,OBJC_DISABLE_INITIALIZE_FORK_SAFETY
setenv = PYTHONDONTWRITEBYTECODE=1
deps = -r requirements.txt
commands = python3 manage.py test

[testenv:py3]
basepython = python3

[testenv:black]
basepython = python3
usedevelop = false
deps = black
changedir = {toxinidir}
commands = black --check --diff todo

[testenv:flake8]
basepython = python3
usedevelop = false
deps = flake8
changedir = {toxinidir}
commands = flake8 todo

[testenv:isort]
basepython = python3
usedevelop = false
deps = isort
changedir = {toxinidir}
commands = isort --check-only --diff todo
